### ISSUE TITLE
A filter to check out a user's memes without scrolling the history.

### ISSUE THREAD

**Issue by zatouroff** [Nudes-Token/feedback#14] opened 2022-06-14 21:44 UTC
It'd be nice if you could filter your own memes only. So you can easily see how they're doing. Or being able to see a user's posted meme history.

**Comment by adrian-fjellberg** [comment] 2022-06-15 06:22
Hello @zatouroff 

I think this would be a duplicate of this issue, as having a profile would solve that issue: https://github.com/Nudes-Token/feedback/issues/10

**Closed by adrian-fjellberg** 2022-06-15 06:22 UTC
Labels: duplicate, enhancement
